# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcL1 <- function(e) {
    .Call(`_TestPkg_calcL1`, e)
}

match1 <- function(x, table) {
    .Call(`_TestPkg_match1`, x, table)
}

match2 <- function(x, table) {
    .Call(`_TestPkg_match2`, x, table)
}

prod_cpp <- function(x) {
    .Call(`_TestPkg_prod_cpp`, x)
}

prodMat <- function(x) {
    .Call(`_TestPkg_prodMat`, x)
}

test_ <- function() {
    invisible(.Call(`_TestPkg_test_`))
}

